version: '3'
services:
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: token-exchange
    ports:
      - "5432:5432"
   #volumes:
    #  - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  tokendings:
    env_file:
      - "local.env"
    build: .
    ports:
      - "8080:8080"
  otel:
    image: grafana/otel-lgtm:latest
    ports:
      - "3001:3000"
      - "4317:4317"
      - "4318:4318"
