apiVersion: v1
kind: ConfigMap
metadata:
  name: tokendings-mappings
  namespace: plattformsikkerhet
  labels:
    app: tokendings
    team: plattformsikkerhet
data:
  SUBJECT_TOKEN_MAPPINGS: |
    {
      "https://test.idporten.no/.well-known/openid-configuration": {
        "acr": {
            "idporten-loa-substantial": "Level3",
            "idporten-loa-high": "Level4"
        }
      },
      "https://idporten.no/.well-known/openid-configuration": {
        "acr": {
            "idporten-loa-substantial": "Level3",
            "idporten-loa-high": "Level4"
        }
      }
    }
