apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
  annotations:
    config.linkerd.io/proxy-cpu-request: "50m"
    config.linkerd.io/proxy-memory-request: "50Mi"
    config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "10"
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
      {{#each host}}
        - host: "{{this}}"
      {{/each}}
      rules: []
  port: 8080
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
    cpuThresholdPercentage: 90
  liveness:
    path: /internal/isalive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 300m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        name: {{sqlinstance_name}}
        diskSize: 100
        highAvailability: true
        tier: db-custom-4-15360
        autoBackupHour: 2
        maintenance:
          day: 1
          hour: 1
        databases:
          - name: tokendings
            envVarPrefix: DB

  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}

  env:
  {{#each env}}
    - name: "{{@key}}"
      value: "{{this}}"
  {{/each}}

  envFrom:
    - secret: {{app}}-bearerauth
