app: tokendings
namespace: plattformsikkerhet
team: plattformsikkerhet
ingresses:
  - https://tokendings.prod-gcp.nais.io
host:
  - login.microsoftonline.com
  - oidc.difi.no
env:
  APPLICATION_PROFILE: PROD
  ISSUER_URL: https://tokendings.prod-gcp.nais.io
  SUBJECT_TOKEN_ISSUERS: https://oidc.difi.no/idporten-oidc-provider/.well-known/openid-configuration
  APPLICATION_PORT: 8080
slack_alert_channel: "plattformsikkerhet-alerts-prod"
sqlinstance_name: tokendings-postgres
replicas:
  min: 12
  max: 24
