apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tokenx.fullname" . }}
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    {{- include "tokenx.tokendings.labels" . | nindent 4 }}
data:
  {{- if .Values.tokendings.mapSubjectTokenClaims }}
  SUBJECT_TOKEN_MAPPINGS: |
    {
      "https://test.idporten.no/.well-known/openid-configuration": {
        "acr": {
            "idporten-loa-substantial": "Level3",
            "idporten-loa-high": "Level4"
        }
      },
      "https://idporten.no/.well-known/openid-configuration": {
        "acr": {
            "idporten-loa-substantial": "Level3",
            "idporten-loa-high": "Level4"
        }
      }
    }
  {{- end }}
  {{- if .Values.tokendings.registrationApi.useServiceAccountAuth }}
  AUTH_PROVIDER_CONFIGS: |
    [
      {
        "wellKnownUrl": "{{ .Values.tokendings.registrationApi.authWellKnownUrl | required ".Values.tokendings.registrationApi.authWellKnownUrl is required"}}",
        "allowedSubjects": ["system:serviceaccount:nais-system:tokenx-jwker"]
      }{{- if .Values.tokendings.registrationApi.authOnPremWellKnownUrl }},
      {
        "wellKnownUrl": "{{ .Values.tokendings.registrationApi.authOnPremWellKnownUrl }}",
        "allowedSubjects": ["system:serviceaccount:nais-system:tokenx-jwker"]
      }
      {{- end }}
    ]
  {{- end }}
