{{ if .Values.networkPolicy.enabled }}
apiVersion: nais.io/v1
kind: ReplicationConfig
metadata:
  name: {{ .Release.Name }}-tokendings
  labels:
    {{- include "tokenx.tokendings.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchExpressions:
      - key: team
        operator: Exists
    matchLabels:
      nais.io/type: workload
  resources:
    - template: |
        apiVersion: networking.gke.io/v1alpha3
        kind: FQDNNetworkPolicy
        metadata:
          name: {{ .Release.Name }}-tokendings-fqdn
          annotations:
            fqdnnetworkpolicies.networking.gke.io/aaaa-lookups: "skip"
        spec:
          egress:
            - ports:
                - port: 443
                  protocol: TCP
              to:
                - fqdns:
                    - {{ .Values.tokendings.host }}
          podSelector:
            matchLabels:
              tokenx: enabled
          policyTypes:
            - Egress
{{ end }}
