@startuml
actor ci as ci
participant jwker as "jwker"
collections apps as "apps"
participant tokendings as "tokendings"
database clientstore

==Client Registration==
jwker <-> jwker: load a shared key from secret at startup
/' note right: private key used to verify the assertion '/
ci -> apps : apply ´application´ resource to cluster
jwker -> apps: Create jwks and k8s secret for application in cluster
jwker -> tokendings: POST /registration/client\nwith bearer token
note right: application jwks and signed softwarestatement using shared key (client_id, accessPolicy) as json
tokendings -> tokendings: authenticate jwker and verify signature \n on softwarestatement (keys loaded as secret on startup)
tokendings -> clientstore: store as oauth2 client with allowed grant_types and accessPolicies
tokendings -> jwker: return json of registered client
@enduml
