repository: europe-north1-docker.pkg.dev/nais-io/nais/images

team: nais

networkPolicy:
  enabled: false
  apiServerCIDR:

tokendings:
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 512Mi
      cpu: 400m
  image: tokendings
  tag: latest
  env:
    APPLICATION_PROFILE: "PROD"
    SUBJECT_TOKEN_ISSUERS: ""
    APPLICATION_PORT: "8080"
    AUTH_CLIENT_JWKS: ""
    AUTH_ACCEPTED_AUDIENCE: "tokendings"
    TOKEN_EXPIRY_SECONDS: 900
  additionalOutboundHosts: []
  authWellKnownUrl: ""
  authOnPremWellKnownUrl: ""
  database:
    diskSize: 10
    highAvailability: true
    tier:
    sqlinstance_name: tokendings
  host:
  mapSubjectTokenClaims: false
