CREATE TABLE IF NOT EXISTS CLIENTS_V0 (
    CLIENT_ID varchar(100) PRIMARY KEY,
    JWKS text,
    ACCESS_POLICY_INBOUND text,
    ACCESS_POLICY_OUTBOUND text,
    ALLOWED_SCOPES text,
    ALLOWED_GRANT_TYPES text
);

CREATE TABLE IF NOT EXISTS CLIENTS (
    CLIENT_ID varchar(100) NOT NULL,
    data JSONB NOT NULL,
    PRIMARY KEY (CLIENT_ID)
);
