name: Build master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '15'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Verify Gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew build

  release-notes:
    runs-on: ubuntu-20.04
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
