name: detekt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  detekt:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detekt Codesmell
        uses: natiginfo/action-detekt-all@1.20.0
        with:
          args: >
            -r sarif:reports/detekt.json
            -r txt:reports/detekt.txt
            --jvm-target 16
            --build-upon-default-config
            --config .github/detekt/detekt-config.yml
      - name: Detekt results Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: reports/detekt.json
