name: Build, push and sign
on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
jobs:
  build_push_sign:
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"
    outputs:
      img_to_deploy: ${{ steps.build-push-sign.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # ratchet:actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # ratchet:actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # ratchet:gradle/actions/setup-gradle@v4
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # ratchet:gradle/actions/dependency-submission@v4
      - name: Gradle build
        run: ./gradlew build
      - uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # ratchet:sigstore/cosign-installer@v3
      - name: Verify distroless base image
        run: |
          cosign verify \
          --certificate-identity "keyless@distroless.iam.gserviceaccount.com" \
          --certificate-oidc-issuer "https://accounts.google.com" \
          gcr.io/distroless/java21-debian12:nonroot
      - name: "Build and push image"
        uses: nais/platform-build-push-sign@main # ratchet:exclude
        id: build-push-sign
        with:
          name: tokendings
          google_service_account: gh-tokendings
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push_ghcr: true
          multi-platform: true
