name: Test Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Verify Gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit

      - name: Run the usual CI build (dependency-graph will be generated and submitted post-job)
        run: ./gradlew build
